import {compare} from './phrase-compare.js';
import {contour} from './phrase-contour.js';
const $=id=>document.getElementById(id);
const ref=new Audio();let phrases=[],selected=null,expected=[],recorder,stream,timer,recordURL,refURL,working=false;
try{phrases=JSON.parse(localStorage.getItem('tony-phrases')||'[]');if(!Array.isArray(phrases))phrases=[];phrases=phrases.filter(p=>typeof p?.text==='string'&&typeof p?.meaning==='string');}catch{}
async function api(path,data){const r=await fetch(path,{method:'POST',headers:data instanceof Blob?{}:{'Content-Type':'application/json'},body:data instanceof Blob?data:JSON.stringify(data)});if(!r.ok){const e=await r.json();throw Error(e.error||'Nie udało się wykonać operacji.');}return r;}
function status(text){$('phraseStatus').textContent=text;}
async function melody(blob,reference){
  const ctx=new AudioContext();
  try{const decode=async audio=>{const b=await ctx.decodeAudioData(await audio.arrayBuffer());return contour(b.getChannelData(0),b.sampleRate);};const user=await decode(blob);let pattern=[];if(reference)pattern=await decode(reference);const path=points=>{let next=true;return points.map(p=>{if(p.y===null){next=true;return '';}const command=next?'M':'L';next=false;return `${command}${(20+p.x*560).toFixed(1)},${(180-p.y*160).toFixed(1)}`;}).join(' ');};$('phraseChart').innerHTML=[20,60,100,140,180].map(y=>`<line x1="20" x2="580" y1="${y}" y2="${y}" stroke="#dde2d4" stroke-dasharray="4 5"/>`).join('')+`<path d="${path(pattern)}" fill="none" stroke="#8ba371" stroke-width="3"/><path d="${path(user)}" fill="none" stroke="#df997a" stroke-width="2.5"/>`;$('melodyNote').textContent=user.length?'Przebieg całej frazy: wzorzec zielony, Twoja wymowa pomarańczowa. Wysokość głosu i czas są przeskalowane. Porównaj ruch głosu i pauzy; wykres nie ocenia poszczególnych tonów.':'Nie udało się zmierzyć melodii głosu. Transkrypcja i odsłuch są nadal dostępne.';if(user.length&&!reference)$('melodyNote').textContent='Pokazujemy tylko Twój głos. Wzorzec jest niedostępny; sprawdź połączenie z internetem.';}finally{await ctx.close();}
}
function lock(value){working=value;for(const id of ['addPhrase','phraseList','phraseReference','deletePhrase','phraseUpload','phraseSpeed'])$(id).disabled=value;$('record').disabled=value;}
function resetResult(){$("phraseChart").replaceChildren();$("melodyNote").textContent="Po nagraniu zobaczysz przebieg głosu całej frazy.";$('recognized').textContent='Tutaj pojawi się rozpoznana wypowiedź.';$('recognizedPinyin').textContent='';$('phraseComparison').replaceChildren();$('phraseScore').textContent='Nagraj całą frazę, potem porównaj wynik.';$('phrasePlayback').pause();$('phrasePlayback').hidden=true;}
async function select(i){if(working)return;ref.pause();selected=phrases[i]||null;expected=[];resetResult();if(!selected){$('phraseText').textContent='Dodaj swoją pierwszą frazę';$('phrasePinyin').textContent='';$('phraseMeaning').textContent='';return;}const chosen=selected;$('phraseList').value=String(i);$('phraseText').textContent=selected.text;$('phraseMeaning').textContent=selected.meaning;$('phrasePinyin').textContent='Przygotowuję pinyin…';try{const result=await(await api('/api/pinyin',{text:selected.text})).json();if(selected===chosen){$('phrasePinyin').textContent=result.pinyin;expected=result.syllables;}}catch(e){status(e.message);}}
function list(){const el=$('phraseList');el.replaceChildren();phrases.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.text+(p.meaning?` — ${p.meaning}`:'');el.append(o);});}
$('phraseForm').onsubmit=async e=>{e.preventDefault();if(working)return;const text=$('newPhrase').value.trim(),meaning=$('newMeaning').value.trim();if(!/\p{Script=Han}/u.test(text)){status('Wpisz frazę chińskimi znakami. Pinyin pojawi się automatycznie.');return;}try{await api('/api/pinyin',{text});phrases.push({text,meaning});localStorage.setItem('tony-phrases',JSON.stringify(phrases));list();await select(phrases.length-1);$('phraseForm').reset();status('Fraza zapisana. Odtwórz wzór i spróbuj ją powiedzieć.');}catch(e){status(e.message);}};
$('phraseList').onchange=e=>select(Number(e.target.value));
$('deletePhrase').onclick=()=>{if(!selected||working)return;phrases.splice(phrases.indexOf(selected),1);localStorage.setItem('tony-phrases',JSON.stringify(phrases));list();select(0);};
$('phraseSpeed').onchange=()=>{ref.playbackRate=Number($('phraseSpeed').value);ref.preservesPitch=true;};
$('phraseReference').onclick=async()=>{window.dispatchEvent(new Event('tony-pause-reference'));if($('record').classList.contains('recording')){status('Najpierw zakończ nagranie sylaby.');return;}if(!selected||working){status('Najpierw dodaj lub wybierz frazę.');return;}lock(true);$('phraseRecord').disabled=true;status('Przygotowuję wzór głosowy…');try{const response=await api('/api/reference',{text:selected.text});ref.pause();if(refURL)URL.revokeObjectURL(refURL);refURL=URL.createObjectURL(await response.blob());ref.src=refURL;ref.playbackRate=Number($('phraseSpeed').value);ref.preservesPitch=true;await ref.play();status('Odtwarzam wzór. Możesz zmieniać tempo bez zmiany wysokości głosu.');}catch(e){status(e.message);}finally{lock(false);$('phraseRecord').disabled=false;}};
$('phraseStopReference').onclick=()=>{ref.pause();ref.currentTime=0;};
async function evaluate(blob){window.dispatchEvent(new Event("tony-pause-reference"));lock(true);$('phraseRecord').disabled=true;resetResult();if(recordURL)URL.revokeObjectURL(recordURL);recordURL=URL.createObjectURL(blob);$('phrasePlayback').src=recordURL;$('phrasePlayback').hidden=false;status('Rozpoznaję całą wypowiedź lokalnie… Może to potrwać kilkanaście sekund.');try{const [transcript,reference]=await Promise.allSettled([api('/api/transcribe',blob).then(r=>r.json()),api('/api/reference',{text:selected.text}).then(r=>r.blob())]);await melody(blob,reference.status==='fulfilled'?reference.value:null).catch(()=>{$('melodyNote').textContent='Wykres jest niedostępny dla tego pliku.';});if(transcript.status==='rejected')throw transcript.reason;const result=transcript.value;if(!result.text){status('Nie rozpoznano mowy. Odsłuchaj nagranie i spróbuj ponownie.');return;}$('recognized').textContent=result.text;$('recognizedPinyin').textContent=result.pinyin;const assessment=compare(expected,result.syllables);$('phraseScore').textContent=`${assessment.match}% zgodności rozpoznanych sylab z frazą`;
    for(const pair of assessment.alignment){const item=document.createElement('div');item.className='syllable '+(pair.expected===pair.actual?'matched':'different');const a=document.createElement('strong');a.textContent=pair.expected||'Dodatkowa sylaba';const b=document.createElement('span');b.textContent=pair.actual||'Nie rozpoznano';item.append(a,b);$('phraseComparison').append(item);}status(assessment.match===100?'Rozpoznane sylaby zgadzają się z frazą. Odsłuchaj i porównaj także tony.':'Zaznaczone sylaby różnią się od wzorca. Posłuchaj wolniejszego wzoru i spróbuj ponownie.');
  }catch(e){status(e.message);}finally{lock(false);$('phraseRecord').disabled=false;}}
function stop(){clearTimeout(timer);if(recorder?.state==='recording')recorder.stop();}
$('phraseRecord').onclick=async()=>{if(recorder?.state==='recording'){stop();return;}if(working)return;if(!selected||!expected.length){status('Najpierw wybierz frazę z gotowym pinyin.');return;}if($('record').classList.contains('recording')){status('Najpierw zakończ nagranie pojedynczej sylaby.');return;}lock(true);$('phraseRecord').disabled=true;window.dispatchEvent(new Event("tony-pause-reference"));ref.pause();$('phrasePlayback').pause();$('playback').pause();try{stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);const parts=[];recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());$('phraseRecord').classList.remove('recording');$('phraseRecord').textContent='●  Nagraj całą frazę';evaluate(new Blob(parts,{type:recorder.mimeType}));};recorder.start();$('phraseRecord').disabled=false;$('phraseRecord').classList.add('recording');$('phraseRecord').textContent='■  Zakończ i pokaż transkrypcję';status('Nagrywam. Powiedz całą frazę i kliknij zakończenie. Limit: 20 sekund.');timer=setTimeout(stop,20000);}catch(e){stream?.getTracks().forEach(t=>t.stop());lock(false);$('phraseRecord').disabled=false;status('Nie udało się uruchomić mikrofonu. Sprawdź uprawnienia przeglądarki.');}};
$('phraseUpload').onchange=e=>{if($('record').classList.contains('recording')){status('Najpierw zakończ nagranie sylaby.');e.target.value='';return;}const file=e.target.files[0];if(!file)return;if(!selected||!expected.length){status('Najpierw wybierz frazę z gotowym pinyin.');return;}if(file.size>8*1024*1024){status('Nagranie może mieć maksymalnie 8 MB.');return;}ref.pause();evaluate(file);e.target.value='';};
window.addEventListener('pagehide',()=>{clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());ref.pause();if(recordURL)URL.revokeObjectURL(recordURL);if(refURL)URL.revokeObjectURL(refURL);});
if(!phrases.length)phrases=[{text:'你好，我想学习中文。',meaning:'Cześć, chcę uczyć się chińskiego.'},{text:'请给我一杯水。',meaning:'Proszę o szklankę wody.'}];list();select(0);
